DOCS-10696 May 15 release RC2
mulesoft/docs-api-community-manager pull request #211
Opened 2021-04-15 16:09 UTC by wwarner-salesforce

DOCS-10696 May 15 release RC2

2021-04-28 20:06 UTC, ferferrarazzo approved these changes

2021-04-29 18:03 UTC, ferferrarazzo requested changes

2021-04-29 18:03 UTC, ferferrarazzo commented on modules/ROOT/pages/acm-lightning-components.adoc
> +By default the API console sends requests from the browser through Anypoint to an API. To send requests directly from the browser to an API instance, open *Setup* > *Custom Metadata Type* > *ACM API
Salesforce Community cloud
```suggestion
By default the API console sends requests from the browser through Salesforce Community Cloud to an API. To send requests directly from the browser to an API instance, open *Setup* > *Custom Metadata Type* > *ACM API Console Configuration Metadata* > *Manage ACM API Console Configuration Metadata* > *ACM API Console Configuration* > *Edit* and select *Browser Requests Enabled*. This setting does not affect the mocking service and this applied to all the API instances in the Community.
```

2021-04-29 18:05 UTC, ferferrarazzo approved these changes

2021-04-29 18:08 UTC, wwarner-salesforce commented on modules/ROOT/pages/acm-lightning-components.adoc
> +By default the API console sends requests from the browser through Anypoint to an API. To send requests directly from the browser to an API instance, open *Setup* > *Custom Metadata Type* > *ACM API
Updated. Thank you!

2021-04-29 18:09 UTC, ferferrarazzo approved these changes

2021-04-29 18:09 UTC, merged