W 12626421 add troubleshooting workaround for api doc not displaying jh
mulesoft/docs-api-community-manager pull request #290
Opened 2023-03-02 20:14 UTC by JennyHajee

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2023-03-03 19:34 UTC, ferferrarazzo requested changes

2023-03-03 19:34 UTC, ferferrarazzo commented on modules/ROOT/pages/troubleshooting-api-documentation-not-displaying.adoc
> +. Scroll to *Caching* and uncheck *Enable secure and persistent browser caching to improve performance*.
```suggestion

```
Lets remove this line for now, it is not necessary

2023-03-07 18:43 UTC, ferferrarazzo approved these changes

2023-03-07 22:13 UTC, bjoson-mulesoft approved these changes

2023-03-07 22:27 UTC, merged